"""first

Revision ID: 97321bb302c5
Revises: 
Create Date: 2021-12-11 14:25:19.888504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97321bb302c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
